# 190502 - 동기와 비동기

### blocking 

- 함수 하나가 다음함수가 실행되지 못하게 막고있음.

- 파이썬은 blocking으로 동작함. (동기적)

```python
from time import sleep

def sleep_3s():
    sleep(3)
    print("wake up!")

print("start!")
sleep_3s() # 함수가 완료되야 다음함수가 실행됨.
print("finish?")
```

```bash
$ python block.py
start!
wake up!
finish?
```

- 자바스크립트는 non blocking으로 동작함 (동기)

```javascript
const nothing = () => {console.log("wakeup")}

console.log("start!!")
setTimeout(nothing, 3000) // 3초
console.log("finish")
```

```bash
$ node block.js
start!!
finish
wakeup
```

- non blocking으로 동작해서 문제발생

```javascript
const makeOrder = function(order){
    let coffee

    setTimeout(function(){
        coffee = order
    },3000)
    return coffee
}
const coffee = makeOrder("Americano")
console.log(coffee)
```

```bash
$ node non.js
undefined
```

- 해결방법1 - callback 사용(사용자가 함수를 줌)

```javascript
const makeOrder = function(order, serve){
    let coffee

    setTimeout(function(){
        coffee = order
        serve(coffee)
    },3000)
    return coffee
}

const coffee = makeOrder("Americano", console.log)
```

```bash
$ node callback.js
Americano
```

- 해결방법2 - promise 사용(이미 만들어져 있는 것을 받음)

```javascript
// 1. 오더를 받는다.
// 2. 종업원이 약속한다.
// 3-1. 다 만들면 resolve로 커피를 주고
// 3-2. 문제가 있으면 reject로 알려준다.

const makeOrder = (order) => new Promise((resolve, reject) => {
        let coffee 

        setTimeout(function(){
            if (order === undefined){
                // 실패할 경우(문제생김)
                reject("잘못 주문됨")
            } else {
                // 주문 잘됨
                coffee = order
                resolve(coffee)
            }
        }, 3000) // timeout 정해주기
    })

// makeOrder()
makeOrder("Americano")
.then((coffee)=>{console.log(coffee)})
.catch((error)=>{console.log(error)})
```

```bash
$ node promise.js
Americano
```

만약 makeOrder에 값을 넣지 않으면

```bash
$ node promise.js
잘못 주문됨
```

